apiVersion: v1
kind: Service
metadata:
  name: zoneminder-web
  labels:
    app: zoneminder
spec:
  ports:
    - port: 80
  selector:
    app: zoneminder
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zoneminder-content
  labels:
    app: zoneminder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zoneminder-content
  labels:
    app: zoneminder
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /vault101/k8s/zoneminder/content
    server: 192.168.1.3
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zoneminder
  labels:
    app: zoneminder
spec:
  selector:
    matchLabels:
      app: zoneminder
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zoneminder
        tier: frontend
    spec:
      containers:
      - image: quantumobject/docker-zoneminder
        name: docker-zoneminder
        resources:
          limits:
            cpu: 2
        env:
        - name: TZ
          value: "America/New_York"
        ports:
        - containerPort: 80
          name: zoneminder
        volumeMounts:
        - name: zoneminder-content
          mountPath: /content
        - name: zoneminder-config
          mountPath: /config
        - name: shm
          mountPath: /dev/shm
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
      - name: zoneminder-content
        persistentVolumeClaim:
          claimName: zoneminder-content
