apiVersion: v1
kind: PersistentVolume
metadata:
  name: zoneminder-config
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /vault101/k8s/zoneminder/config
    server: 192.168.1.3

