apiVersion: v1
kind: PersistentVolume
metadata:
  name: zoneminder-content
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /vault101/k8s/zoneminder/content
    server: 192.168.1.3
